---
{{- define "mychart.labels" }}
  labels:
    generator: helm
    date: {{ now | htmlDate }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" }}
data:
  myvalue: "Hello World"
  {{- $relName := .Release.Name -}}
  {{- with .Values.favourite }}
  drink: {{ .drink | title |quote }}
  food: {{ .food | title | quote }}
  {{- if eq .drink "coffee" }}
  mug: true
  {{- end }}
  release: {{ $relName }}
  {{- end}}
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
     {{ $index }}: {{ $topping | title | quote }}
    {{- end}}
