---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favourite }}
  drink: {{ .drink | title |quote }}
  food: {{ .food | title | quote }}
  {{- if eq .drink "coffee" }}
  mug: true
  {{- end }}
  {{- end}}
