---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" . }}
  {{- include "mychart.app" . | indent 4 }}
data:
  myvalue: "Hello World"
  {{- $relName := .Release.Name -}}
  {{- with .Values.favourite }}
  drink: {{ .drink | title |quote }}
  food: {{ .food | title | quote }}
  {{- if eq .drink "coffee" }}
  mug: true
  {{- end }}
  release: {{ $relName }}
  {{- end}}
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
     {{ $index }}: {{ $topping | title | quote }}
    {{- end}}
  {{- include "mychart.app" . | indent 2 }}
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
    {{ $files.Get .}}
  {{- end}}  
