---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favourite.drink | title |quote }}
  food: {{ .Values.favourite.food | title | quote }}
  {{ if eq .Values.favourite.drink "coffee" }}mug: true {{ end }}
